//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Achivement
{
	public virtual string Imagine
	{
		get;
		set;
	}

	public virtual string Discription
	{
		get;
		set;
	}

	public virtual bool Status
	{
		get;
		set;
	}

	public Achivement(string Disription, string Imagine, bool Status)
	{
	}

	public virtual void GetInfo()
	{
		throw new System.NotImplementedException();
	}

}

