//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Advert
{
	public virtual int Key
	{
		get;
		set;
	}

	public virtual string Name
	{
		get;
		set;
	}

	public virtual int Date
	{
		get;
		set;
	}

	public virtual string Discription
	{
		get;
		set;
	}

	public virtual string GetInfo()
	{
		throw new System.NotImplementedException();
	}

	public Advert(int Date, string Discription, int Key, string Name)
	{
	}

	public virtual void ChangeDicription()
	{
		throw new System.NotImplementedException();
	}

}

