//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class User
{
	public virtual string Login
	{
		get;
		set;
	}

	public virtual string Password
	{
		get;
		set;
	}

	public virtual string Summary
	{
		get;
		set;
	}

	public virtual float Rating
	{
		get;
		set;
	}

	public virtual string Name
	{
		get;
		set;
	}

	public virtual string Surname
	{
		get;
		set;
	}

	public virtual string Email
	{
		get;
		set;
	}

	public virtual string Phone
	{
		get;
		set;
	}

	public  enum Achivments
	{
		get;
		set;
	}

	public User(string Email, string Login, string Name, string Password, string Phone, float Rating, string Summary, string Surname)
	{
	}

	public virtual string GetInfo()
	{
		throw new System.NotImplementedException();
	}

	public virtual void ChangeEmail()
	{
		throw new System.NotImplementedException();
	}

	public virtual void ChangeLogin()
	{
		throw new System.NotImplementedException();
	}

	public virtual void ChangeName()
	{
		throw new System.NotImplementedException();
	}

	public virtual void ChangePassword()
	{
		throw new System.NotImplementedException();
	}

	public virtual void SetPhone()
	{
		throw new System.NotImplementedException();
	}

	public virtual void SetSummary()
	{
		throw new System.NotImplementedException();
	}

	public virtual void SetSurname()
	{
		throw new System.NotImplementedException();
	}

}

